// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Entity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            AdSoyad = "Eray Gülüçmen",
                            ConcurrencyStamp = "54bf1b21-454c-4399-b5c8-013cb40f22c6",
                            Email = "eray@mail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ERAY@MAIL.COM",
                            NormalizedUserName = "ERAY@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEB8aGjlUDnyaqOrLLP2+GKXahauPLkH4+c9v+0Klz0ywa+NB1o0z9BiRl9aMR19YPA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "78df974d-498d-4bc6-89f0-e4272d4c70db",
                            TwoFactorEnabled = false,
                            UserName = "eray@mail.com"
                        });
                });

            modelBuilder.Entity("Entity.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AlmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kurum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Certificates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AktifMi = true,
                            AlmaTarihi = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Baslik = "International Software Expertise",
                            Kurum = "Infotech Academy",
                            Path = "/pdfs/InfotechAcademy_InternationalSoftwareExpertise_2025.pdf",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            AktifMi = true,
                            AlmaTarihi = new DateTime(2025, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Baslik = "Yazılım Uzmanlığı Eğitimi",
                            Kurum = "Mudanya Üniversitesi",
                            Path = "/pdfs/MudanyaUniversitesi_YazilimUzmanligi_2025.pdf",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 3,
                            AktifMi = true,
                            AlmaTarihi = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Baslik = "Yazılım Uzmanlığı (MSCD)",
                            Kurum = "Infotech Academy",
                            Path = "/pdfs/InfotechAcademy_YazilimUzmanligiMSCD_2025.pdf",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 4,
                            AktifMi = true,
                            AlmaTarihi = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Baslik = "ReactJS ile Front-End Uygulamaları Geliştirme",
                            Kurum = "Infotech Academy",
                            Path = "/images/InfotechAcademy_ReactJSFrontEnd_2025.jpg",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 5,
                            AktifMi = true,
                            AlmaTarihi = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Baslik = "Yazılım Uzmanlığı (MSCD)",
                            Kurum = "Infotech Academy",
                            Path = "/images/InfotechAcademy_YazilimUzmanligiMSCD_2025.jpg",
                            UserId = "1"
                        });
                });

            modelBuilder.Entity("Entity.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Yazılımcı olmanın ötesinde, 15 yıllık köklü donanım bilgisiyle bilgisayarın çalışma prensibini donanım seviyesinde anlıyorum. Server optimizasyonları ve ağ mimarisi konularında yüksek tecrübeye sahibim.",
                            IconPath = "fas fa-server",
                            IsActive = true,
                            Title = "Sistem & Donanım"
                        });
                });

            modelBuilder.Entity("Entity.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GondermeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OkunduMu")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "Hoca / Danışman",
                            Email = "hoca@universite.edu.tr",
                            GondermeTarihi = new DateTime(2026, 6, 8, 16, 9, 32, 172, DateTimeKind.Local).AddTicks(6450),
                            Konu = "Proje Değerlendirmesi",
                            Mesaj = "Eray, projelerindeki mimari yaklaşımın ve temiz kod prensiplerine uyumun gerçekten çok başarılı. Portfolyon harika görünüyor, başarılarının devamını dilerim.",
                            OkunduMu = false
                        });
                });

            modelBuilder.Entity("Entity.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EklemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teknolojiler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "TikTok ajans yönetimi için geliştirilen devasa ölçekli bir portal. Kompleks veritabanı şemalarının tasarımı, rol bazlı yetkilendirme altyapısı ve gelişmiş raporlama özellikleri ile ajansın tüm operasyonel yükünü hafifleten bir backend mimarisi kurgulandı.",
                            AktifMi = true,
                            Baslik = "Black Ajans Yönetim Portalı",
                            EklemeTarihi = new DateTime(2026, 6, 8, 16, 9, 32, 172, DateTimeKind.Local).AddTicks(5496),
                            Link = "",
                            Resim = "https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
                            Teknolojiler = "C#, .NET 8 API, MSSQL, Identity",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Yapay zeka algoritmalarıyla çalışan yenilikçi kıyafet deneme uygulamasının backend servisleri. Fotoğraf işleme kuyrukları (RabbitMQ), mikroservis mimarisi ve yüksek trafikli anlık bildirim altyapısı kodlandı.",
                            AktifMi = true,
                            Baslik = "Sanal Kabin (Virtual Try-On)",
                            EklemeTarihi = new DateTime(2026, 6, 8, 16, 9, 32, 172, DateTimeKind.Local).AddTicks(5528),
                            Link = "",
                            Resim = "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
                            Teknolojiler = "Flutter, Python AI, RabbitMQ, .NET Core",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Modern bir e-ticaret uygulamasının uçtan uca gelişimi. Sepet yönetimi, güvenli ödeme (Iyzico) entegrasyonu, sipariş takip durumu ve detaylı admin paneli ile baştan sona temiz kod (Clean Architecture) prensipleriyle yazıldı.",
                            AktifMi = true,
                            Baslik = "KumanStore",
                            EklemeTarihi = new DateTime(2026, 6, 8, 16, 9, 32, 172, DateTimeKind.Local).AddTicks(5532),
                            Link = "https://github.com/ErGu14/KumanStore",
                            Resim = "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
                            Teknolojiler = ".NET 8, Blazor WASM, Iyzico API, Clean Arch",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Güvenli ve hızlı e-ödeme altyapısı sistemi. REST API üzerinden bakiye yönetimi, işlem geçmişi ve sanal POS simülasyonu özellikleri barındırır.",
                            AktifMi = true,
                            Baslik = "KumanPay",
                            EklemeTarihi = new DateTime(2026, 6, 8, 16, 9, 32, 172, DateTimeKind.Local).AddTicks(5536),
                            Link = "https://github.com/ErGu14/KumanPay",
                            Resim = "https://images.unsplash.com/photo-1563013544-824ae1b704d3?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
                            Teknolojiler = ".NET 8, Web API, MSSQL",
                            UserId = "1"
                        });
                });

            modelBuilder.Entity("Entity.RecentTechnology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecentTechnologies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "C# & .NET 8"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Entity Framework Core"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Blazor WebAssembly"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "MS SQL Server"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "RESTful API Geliştirme"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "JWT & Identity Auth"
                        });
                });

            modelBuilder.Entity("Entity.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hakkimda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SiteSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "Eray Gülüçmen",
                            CvPath = "/cv/Eray_Gulucmen_CV_TR.pdf",
                            Hakkimda = "Modern backend teknolojileri (.NET ekosistemi, C#) ile ölçeklenebilir yazılımlar geliştiren; aynı zamanda 15+ yıllık köklü donanım geçmişiyle sistem mimarisi, ağ temelleri ve ileri seviye bilgisayar optimizasyonu konularına tam hakim bir teknoloji adayıyım. Yazılım geliştirme vizyonumu, derin IT ve donanım yapılandırma bilgisiyle harmanlayarak, uçtan uca hızlı ve yenilikçi çözümler üretmeyi hedefliyorum. İstanbul Bilgi Üniversitesi'nde Bilgisayar Programcılığı okuyorum. En büyük hedefim Senior Full Stack Yazılımcı olmaktır.",
                            ProfilFoto = "/images/foto.jpg",
                            Unvan = "Yazılım Geliştirici.,.NET Backend Uzmanı.,Sistem Mimarı.,Donanım Uzmanı.,Veritabanı Optimizasyon Uzmanı.,RESTful API Geliştiricisi.",
                            UserId = "1"
                        });
                });

            modelBuilder.Entity("Entity.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconPath = "fas fa-database",
                            IsActive = true,
                            Items = "C# 12 / .NET 8\nASP.NET Core Web API\nEntity Framework Core\nMS SQL Server & T-SQL\nLINQ & Asynchronous Programming\nClean Architecture & SOLID\nJWT Authentication & Identity",
                            Title = "Backend & API"
                        },
                        new
                        {
                            Id = 2,
                            IconPath = "fas fa-desktop",
                            IsActive = true,
                            Items = "Blazor WebAssembly / Server\nReact.js & Next.js\nHTML5, CSS3, JavaScript (ES6+)\nBootstrap 5 & Tailwind CSS\nUI/UX Prensipleri\nResponsive (Mobil Uyumlu) Tasarım\nDOM Manüpilasyonu & Animations",
                            Title = "Frontend & UI"
                        },
                        new
                        {
                            Id = 3,
                            IconPath = "fas fa-tools",
                            IsActive = true,
                            Items = "Git & GitHub\nVisual Studio & VS Code\nPostman & Swagger (API Testing)\nSistem Mimarisi Kurulumu\nAğ (Network) Yapılandırması\nİleri Seviye Donanım Optimizasyonu\nAgile / Scrum Metodolojileri",
                            Title = "Araçlar & Diğer"
                        });
                });

            modelBuilder.Entity("Entity.SocialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlatformAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SocialMedias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconPath = "fab fa-linkedin",
                            Link = "https://linkedin.com/in/eray-gulucmen-704b0a32a",
                            PlatformAd = "LinkedIn",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2,
                            IconPath = "fab fa-github",
                            Link = "https://github.com/ErGu14",
                            PlatformAd = "GitHub",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 3,
                            IconPath = "fas fa-briefcase",
                            Link = "https://bionluk.com/kumanstack",
                            PlatformAd = "Bionluk",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 4,
                            IconPath = "fab fa-instagram",
                            Link = "https://instagram.com",
                            PlatformAd = "Instagram",
                            UserId = "1"
                        },
                        new
                        {
                            Id = 5,
                            IconPath = "fab fa-tiktok",
                            Link = "https://tiktok.com",
                            PlatformAd = "TikTok",
                            UserId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entity.Certificate", b =>
                {
                    b.HasOne("Entity.AppUser", "User")
                        .WithMany("Certificates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.Project", b =>
                {
                    b.HasOne("Entity.AppUser", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.SiteSettings", b =>
                {
                    b.HasOne("Entity.AppUser", "AppUser")
                        .WithOne("SiteSettings")
                        .HasForeignKey("Entity.SiteSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Entity.SocialMedia", b =>
                {
                    b.HasOne("Entity.AppUser", "User")
                        .WithMany("SocialMedias")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Entity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Entity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entity.AppUser", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Projects");

                    b.Navigation("SiteSettings")
                        .IsRequired();

                    b.Navigation("SocialMedias");
                });
#pragma warning restore 612, 618
        }
    }
}
